config/routes.rb
Rails.application.routes.draw do
	root 'tic_tac_toe#home'
	get '/tic_tac_toe/prize' => 'tic_tac_toe#prize'
	get '/tic_tac_toe/points' => 'tic_tac_toe#points'
	
	resources :scores
	
	post '/tic_tac_toe' => 'tic_tac_toe#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tic_tac_toe_controller.rb
class TicTacToeController < ApplicationController
	def home

	end
	def prize
	end
	def points
		@score = Score.all
	end
	def create
		@score = Score.new(points_params)
		
		@score.save
		render :prize
		
	end
	
	private
		def points_params
			params.permit(:name, :points)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tic_tac_toe_helper.rb
module TicTacToeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

	<body>
		<%= render 'shared/header' %>
		
		<%= yield %>
	
		<%= render 'shared/footer' %>
	</body>
	<% # needs to load last causes issues with javascript selectors %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/shared/_board.html.erb
<% #  this is the layout for the tic tac toe board  %>

<% for i in 0...9 do %>
	<div class="tac" id='<%= i %>' >
		<div class="toe"></div>
		<div class="x-second-half hide"></div>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
	<p>by Luis Perez 2020</p>
</footer>

app/views/shared/_header.html.erb
<header>
	<h1>My Ruby Project</h1>
	<nav>
		<a href='/'>Welcome</a>
		<a href='/tic_tac_toe/points'>Scoreboard</a>
	</nav>
</header>

app/views/shared/_store_points.html.erb
<div class="store_points">
  <div class="container">
    
	<%= form_with url: tic_tac_toe_path, local: true do |form| %>
		<div class="field">
			<%= form.label :name %><br>
			<%= form.text_area :name %>
		</div>
		<div class="field">
			<%= form.label :points %><br>
			<%= form.text_area :points %>
		</div>
		<div class="actions">
			<%= form.submit "Create" %>
		</div>
	<% end %>

  </div>
</div>

app/views/tic_tac_toe/home.html.erb
<main>
	<h2>Welcome to Tic Tac Toe!</h2>
	<p>You will have more fun than Minecraft</p>
	<section>
		<%= render 'shared/board' %>
	</section>
	<section>
		<%= render 'shared/store_points' %>
	</section>
</main>

app/views/tic_tac_toe/points.html.erb
<main>
	<% @score.each do |s| %>
		<div class="points-container">
			<p><span>Name: </span><%= s.name %></p>
			<p><span>Points: </span><%= s.points %></p>
		</div>
	<% end %>
</main>

app/views/tic_tac_toe/prize.html.erb
<main class="prize">
	<h1>YOU'RE WINNER!</h1>
</main>